/* ZonaGTA6TV V14 — Smart News Radar + story clustering */
const NEWS_FEEDS=[
{name:'Google News — GTA 6',url:'https://news.google.com/rss/search?q=GTA%206%20OR%20GTA%20VI&hl=es-419&gl=CO&ceid=CO:es-419'},
{name:'Google News — Rockstar Games',url:'https://news.google.com/rss/search?q=Rockstar%20Games%20GTA%206&hl=es-419&gl=CO&ceid=CO:es-419'},
{name:'Google News — GTA 6 filtración',url:'https://news.google.com/rss/search?q=GTA%206%20filtraci%C3%B3n%20OR%20leak&hl=es-419&gl=CO:es-419'},
{name:'Google News — GTA VI trailer release',url:'https://news.google.com/rss/search?q=GTA%20VI%20trailer%20release%20date&hl=es-419&gl=CO&ceid=CO:es-419'}
];
let radarItems=[], storyClusters=[];
const radar=$id=>document.getElementById($id);
function radarStatus(t,err=false){const e=radar('radarStatus');if(e){e.textContent=t;e.classList.toggle('error',err)}}
function cleanText(s){const d=document.createElement('div');d.innerHTML=s||'';return d.textContent.replace(/\s+/g,' ').trim()}
function hoursAgo(date){const n=(Date.now()-new Date(date).getTime())/3600000;return isFinite(n)?Math.max(0,Math.round(n)):99999}
function classify(title,desc=''){const t=(title+' '+desc).toLowerCase();if(/rockstar (games )?(announces|confirms)|official|officially|confirmado|oficial/.test(t))return 'OFICIAL';if(/leak|leaked|filtr|rumor|rumour|insider|datamine|hack|stolen/.test(t))return 'FILTRACIÓN/RUMOR';return 'NOTICIA'}
function tokens(s){return new Set((s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(x=>x.length>3&&!['gta','grand','theft','auto','rockstar','games'].includes(x)))}
function similarity(a,b){const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return 0;let n=0;A.forEach(x=>{if(B.has(x))n++});return n/(A.size+B.size-n)}
function score(item){const t=(item.title+' '+item.description).toLowerCase();let s=0;if(/gta\s*6|gta\s*vi|grand theft auto vi/.test(t))s+=30;if(/rockstar|take-two|take two/.test(t))s+=20;if(/trailer|release|fecha|date|delay|retras|leak|filtr|map|gameplay|vehicles|vehiculos|lucia|jason/.test(t))s+=15;const h=hoursAgo(item.pubDate);s+=h<6?25:h<24?18:h<72?10:0;if(item.type==='OFICIAL')s+=12;if(item.type==='FILTRACIÓN/RUMOR')s+=6;return s}
async function fetchFeed(feed){const urls=[`https://api.allorigins.win/raw?url=${encodeURIComponent(feed.url)}`,`https://corsproxy.io/?url=${encodeURIComponent(feed.url)}`];let last;for(const u of urls){try{const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const text=await r.text();if(!text.includes('<item')&&!text.includes('<entry'))throw Error('RSS inválido');return {feed,text}}catch(e){last=e}}throw last||Error('No se pudo consultar RSS')}
function parseRSS(xml,feed){const doc=new DOMParser().parseFromString(xml,'text/xml');return [...doc.querySelectorAll('item')].map(x=>({title:cleanText(x.querySelector('title')?.textContent),description:cleanText(x.querySelector('description')?.textContent),url:x.querySelector('link')?.textContent?.trim()||'',pubDate:x.querySelector('pubDate')?.textContent||'',source:feed.name})).filter(x=>x.title&&x.url)}
function clusterStories(items){const clusters=[];for(const item of items){let best=null,bs=0;for(const c of clusters){const sim=similarity(item.title,c.items[0].title);if(sim>bs){bs=sim;best=c}}if(best&&bs>=.34){best.items.push(item);best.score=Math.max(best.score,item.score)}else clusters.push({items:[item],score:item.score})}return clusters.sort((a,b)=>b.score-a.score).slice(0,12)}
async function refreshRadar(){const hours=Number(radar('radarHours')?.value||72);radarStatus('Buscando y agrupando noticias…');let all=[],failed=0;for(const feed of NEWS_FEEDS){try{const r=await fetchFeed(feed);all.push(...parseRSS(r.text,r.feed))}catch(e){failed++}}const seen=new Set();radarItems=all.map(x=>({...x,type:classify(x.title,x.description)})).filter(x=>hoursAgo(x.pubDate)<=hours&&!seen.has(x.url)&&seen.add(x.url)).map(x=>({...x,score:score(x)})).sort((a,b)=>b.score-a.score).slice(0,50);storyClusters=clusterStories(radarItems);renderRadar();radarStatus(radarItems.length?`✓ ${radarItems.length} resultados · ${storyClusters.length} historias agrupadas${failed?' · '+failed+' fuente(s) no respondieron':''}.`:'No se encontraron resultados. Prueba otra ventana.',!radarItems.length)}
function renderRadar(){const box=radar('radarResults');if(!box)return;box.innerHTML=storyClusters.map((c,i)=>{const x=c.items[0];const sources=[...new Set(c.items.map(z=>z.source))];return `<article class="newsCard"><div class="newsTop"><span class="newsBadge ${x.type.includes('FIL')?'leak':x.type==='OFICIAL'?'official':''}">${x.type}</span><span>${hoursAgo(x.pubDate)<9999?`hace ${hoursAgo(x.pubDate)} h`:''}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.description).slice(0,240)}${x.description.length>240?'…':''}</p><div class="newsMeta">${c.items.length} cobertura(s) · ${esc(sources.join(' · '))} · relevancia ${c.score}</div><div class="actions compact"><button data-cluster="${i}" class="primary">⚡ CREAR SHORT + LARGO</button><button data-short="${i}" class="secondary">🎬 SOLO SHORT</button><a class="secondary linkBtn" href="${esc(x.url)}" target="_blank" rel="noopener">🔗 Fuente</a></div></article>`}).join('');box.querySelectorAll('[data-cluster]').forEach(b=>b.onclick=()=>useCluster(+b.dataset.cluster,'both'));box.querySelectorAll('[data-short]').forEach(b=>b.onclick=()=>useCluster(+b.dataset.short,'short'))}
function useCluster(i,mode='both'){const c=storyClusters[i];if(!c)return;const x=c.items[0];const coverage=c.items.slice(0,6).map(z=>`- ${z.title} | ${z.source} | ${z.url}`).join('\n');const topic=`${x.title}\n\nResumen: ${x.description}\nTipo detectado: ${x.type}\nCobertura relacionada:\n${coverage}\n\nINSTRUCCIÓN EDITORIAL: separa hechos de rumores. No presentes una filtración como confirmada. Usa solo información sustentada por las fuentes y conserva los enlaces.`;const t=document.getElementById('topic');if(t)t.value=topic;const type=document.getElementById('type');if(type)type.value=x.type==='FILTRACIÓN/RUMOR'?'Rumor / filtración':'Noticia';window.ZGTA6_SELECTED_STORY={mode,title:x.title,source:x.source,url:x.url,type:x.type,coverage:c.items.map(z=>({title:z.title,source:z.source,url:z.url}))};document.getElementById('generator')?.scrollIntoView({behavior:'smooth',block:'start'});if(mode==='both' && typeof createV15FromSelectedStory==='function'){setTimeout(()=>createV15FromSelectedStory(),300)}else if(typeof generate==='function')setTimeout(()=>generate(),300)}
window.addEventListener('DOMContentLoaded',()=>{radar('refreshRadarBtn')?.addEventListener('click',refreshRadar);radar('autoRadarBtn')?.addEventListener('click',async()=>{await refreshRadar();if(storyClusters[0])useCluster(0,'both')});radar('smartBatchBtn')?.addEventListener('click',async()=>{await refreshRadar();const topics=storyClusters.slice(0,Number(radar('smartBatchCount')?.value||5)).map(c=>c.items[0].title);const b=document.getElementById('batchTopics');if(b)b.value=topics.join('\n');document.getElementById('batch')?.scrollIntoView({behavior:'smooth'})})});
